# pytorch fundamental

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(f"Is CUDA supported by this system? {torch.cuda.is_available()}")

Is CUDA supported by this system? True


In [31]:
print(f"CUDA version: {torch.version.cuda}")

# Storing ID of current CUDA device
cuda_id = torch.cuda.current_device()
print(f"ID of current CUDA device: {torch.cuda.current_device()}")
	
print(f"Name of current CUDA device: {torch.cuda.get_device_name(cuda_id)}")


CUDA version: 12.1
ID of current CUDA device: 0
Name of current CUDA device: NVIDIA GeForce RTX 3050 Laptop GPU


In [32]:
print(torch.__version__)

2.4.1+cu121


## intro to tensors

In [5]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
vector = torch.tensor([7,7])
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
MATRIX = torch.tensor([
    [7,8],
    [9,10]    
])

MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
#   TENSOR
TENSOR = torch.tensor([
    [[1,2,3],
     [4,5,6],
      [7,8,9]]
                       ])

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8283, 0.9763, 0.8209, 0.7218],
        [0.8687, 0.7220, 0.6967, 0.6903],
        [0.6919, 0.6633, 0.0733, 0.5921]])

In [16]:
random_tensor.ndim,random_tensor.shape

(2, torch.Size([3, 4]))

In [17]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
ones.dtype

torch.float32

In [20]:
#creating a range of tensors and tensor like
range_tensor = torch.arange(0,10,2)
tensors_like = torch.zeros_like(input=range_tensor)

In [21]:
range_tensor, tensors_like

(tensor([0, 2, 4, 6, 8]), tensor([0, 0, 0, 0, 0]))

## tensor dtypes

In [22]:
x = torch.tensor([3,4],dtype=torch.uint8, )

In [23]:
x.dtype

torch.uint8

In [24]:
random_tensor

tensor([[0.8283, 0.9763, 0.8209, 0.7218],
        [0.8687, 0.7220, 0.6967, 0.6903],
        [0.6919, 0.6633, 0.0733, 0.5921]])

In [25]:
print(f'datatype of tensor: {random_tensor.dtype} \nshape: {random_tensor.shape}\n{random_tensor.device}')

datatype of tensor: torch.float32 
shape: torch.Size([3, 4])
cpu


In [26]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [27]:
tensor * 10

tensor([10, 20, 30])

In [28]:
torch.mul(tensor , 10)

tensor([10, 20, 30])

In [29]:
# martix multiplicaton or dot product
torch.matmul(tensor,tensor+10)

tensor(74)

In [30]:
tensor @ (tensor+10)

tensor(74)

In [86]:
random_tensor.mT

tensor([[0.3734, 0.7552, 0.6928],
        [0.7691, 0.8004, 0.6868],
        [0.7026, 0.1024, 0.8230],
        [0.6693, 0.3585, 0.3263]])

In [96]:
## tensor aggreagation
x = torch.arange(0,100,10)
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.mean(x)


#arrange gives dtype int64 but mean need float

In [99]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [102]:
x.argmax() #position of the maximum number

tensor(9)

### reshaping, stacking, squeeze and unsqueeze, permute

In [103]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [108]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [109]:
x__reshaped = x_reshaped.reshape(9,1)
x__reshaped, x__reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [113]:
z = x.view(9,1)
z,z.shape                   #changing z will change x

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [126]:
# stacking tensors on top
x_vstacked = torch.stack([x, x, x, x], dim=0)
x_hstacked = torch.stack([x, x, x, x], dim=1)

In [127]:
x_vstacked, x_hstacked

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]))

In [134]:
x_reshaped = x.reshape(1,9)
x_reshaped.shape

torch.Size([1, 9])

In [135]:
x.squeeze().shape

torch.Size([9])

In [136]:
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [147]:
y = torch.squeeze(x)
y.shape

torch.Size([9])

In [148]:
y = torch.unsqueeze(y,dim=0)

In [149]:
y

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [150]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [151]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

### GPU and TESNORS

In [33]:
!nvidia-smi

Mon Oct 14 19:54:40 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 546.80                 Driver Version: 546.80       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   64C    P8              10W /  35W |     95MiB /  4096MiB |     20%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [34]:
torch.cuda.is_available()

True

In [36]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [39]:
torch.cuda.device_count()

1

In [40]:
tensor = torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [43]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [44]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [48]:
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3], dtype=int64)

: 