# pytorch fundamental

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [55]:
import torch

print(f"Is CUDA supported by this system? {torch.cuda.is_available()}")
print(f"CUDA version: {torch.version.cuda}")

# Storing ID of current CUDA device
cuda_id = torch.cuda.current_device()
print(f"ID of current CUDA device: {torch.cuda.current_device()}")
	
print(f"Name of current CUDA device: {torch.cuda.get_device_name(cuda_id)}")


Is CUDA supported by this system? True
CUDA version: 12.1
ID of current CUDA device: 0
Name of current CUDA device: NVIDIA GeForce RTX 3050 Laptop GPU


In [3]:
print(torch.__version__)

2.4.1+cu121


## intro to tensors

In [63]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [12]:
scalar.ndim

0

In [14]:
scalar.item()

7

In [16]:
vector = torch.tensor([7,7])
vector.ndim

1

In [17]:
vector.shape

torch.Size([2])

In [18]:
MATRIX = torch.tensor([
    [7,8],
    [9,10]    
])

MATRIX.ndim

2

In [19]:
MATRIX.shape

torch.Size([2, 2])

In [21]:
MATRIX[0]

tensor([7, 8])

In [22]:
#   TENSOR
TENSOR = torch.tensor([
    [[1,2,3],
     [4,5,6],
      [7,8,9]]
                       ])

In [24]:
TENSOR.shape

torch.Size([1, 3, 3])

In [64]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3734, 0.7691, 0.7026, 0.6693],
        [0.7552, 0.8004, 0.1024, 0.3585],
        [0.6928, 0.6868, 0.8230, 0.3263]])

In [27]:
random_tensor.ndim,random_tensor.shape

(2, torch.Size([3, 4]))

In [31]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
ones.dtype

torch.float32

In [39]:
#creating a range of tensors and tensor like
range_tensor = torch.arange(0,10,2)
tensors_like = torch.zeros_like(input=range_tensor)

In [40]:
range_tensor, tensors_like

(tensor([0, 2, 4, 6, 8]), tensor([0, 0, 0, 0, 0]))

## tensor dtypes

In [45]:
x = torch.tensor([3,4],dtype=torch.uint8, )

In [46]:
x.dtype

torch.uint8

In [47]:
random_tensor

tensor([[[0.7363, 0.8991, 0.7123,  ..., 0.0853, 0.4279, 0.9614],
         [0.3458, 0.8143, 0.2023,  ..., 0.6940, 0.0944, 0.9884],
         [0.7027, 0.0870, 0.9956,  ..., 0.4283, 0.8967, 0.9688],
         ...,
         [0.1037, 0.2445, 0.9003,  ..., 0.3142, 0.3488, 0.5523],
         [0.1708, 0.4059, 0.5465,  ..., 0.5584, 0.2087, 0.9148],
         [0.4347, 0.9384, 0.2829,  ..., 0.6536, 0.2417, 0.6861]],

        [[0.7378, 0.1578, 0.2434,  ..., 0.3903, 0.0648, 0.3953],
         [0.9397, 0.2750, 0.5651,  ..., 0.2697, 0.3764, 0.8429],
         [0.2210, 0.7225, 0.7731,  ..., 0.6107, 0.4852, 0.4178],
         ...,
         [0.3244, 0.5740, 0.1633,  ..., 0.1733, 0.7467, 0.6743],
         [0.5293, 0.1249, 0.0877,  ..., 0.0615, 0.0331, 0.6139],
         [0.5743, 0.0350, 0.9086,  ..., 0.9800, 0.7130, 0.8580]],

        [[0.1051, 0.2119, 0.8691,  ..., 0.0664, 0.4593, 0.3143],
         [0.6397, 0.8920, 0.6509,  ..., 0.8862, 0.6090, 0.8568],
         [0.6944, 0.9006, 0.2662,  ..., 0.4785, 0.0513, 0.

In [57]:
print(f'datatype of tensor: {random_tensor.dtype} \nshape: {random_tensor.shape}\n{random_tensor.device}')

datatype of tensor: torch.float32 
shape: torch.Size([3, 4])
cpu


In [68]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [69]:
tensor * 10

tensor([10, 20, 30])

In [70]:
torch.mul(tensor , 10)

tensor([10, 20, 30])

In [79]:
# martix multiplicaton or dot product
torch.matmul(tensor,tensor+10)

tensor(74)

In [78]:
tensor @ (tensor+10)

tensor(74)

In [86]:
random_tensor.mT

tensor([[0.3734, 0.7552, 0.6928],
        [0.7691, 0.8004, 0.6868],
        [0.7026, 0.1024, 0.8230],
        [0.6693, 0.3585, 0.3263]])

In [96]:
## tensor aggreagation
x = torch.arange(0,100,10)
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.mean(x)


#arrange gives dtype int64 but mean need float

In [99]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [102]:
x.argmax() #position of the maximum number

tensor(9)

### reshaping, stacking, squeeze and unsqueeze, permute

In [103]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [108]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [109]:
x__reshaped = x_reshaped.reshape(9,1)
x__reshaped, x__reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [113]:
z = x.view(9,1)
z,z.shape                   #changing z will change x

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [122]:
# stacking tensors on top
x_vstacked = torch.stack([x, x, x, x], dim=0)
x_hstacked = torch.stack([x, x, x, x], dim=1)

In [124]:
x_vstacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])